export class ChapterList {
    static chalterList: any = [
        {id:1, subject_id:27, code:'CACS351_1', name:'Introduction to Mobile and Mobile Programming'},
        {id:2, subject_id:27, code:'CACS351_2', name:'Introduction to Android Programming'},
        {id:3, subject_id:27, code:'CACS351_3', name:'Designing the User Interface'},
        {id:4, subject_id:27, code:'CACS351_4', name:'Android Activity'},
        {id:5, subject_id:27, code:'CACS351_5', name:'UI Fragments, Menus and Dialogs'},
        {id:6, subject_id:27, code:'CACS351_6', name:'Listview, Gridview and Recyclerview'},
        {id:7, subject_id:27, code:'CACS351_7', name:'Advanced Android Concepts'},
        {id:8, subject_id:27, code:'CACS351_8', name:'Introduction to ios Programming'},
        {id:9, subject_id:28, code:'CACS352_1', name:'Introduction'},
        {id:10, subject_id:28, code:'CACS352_2', name:'Architecture'},
        {id:11, subject_id:28, code:'CACS352_3', name:'Processes'},
        {id:12, subject_id:28, code:'CACS352_4', name:'Communication'},
        {id:13, subject_id:28, code:'CACS352_5', name:'Naming'},
        {id:14, subject_id:28, code:'CACS352_6', name:'Coordination'},
        {id:15, subject_id:28, code:'CACS352_7', name:'Consistency and Replication '},
        {id:16, subject_id:28, code:'CACS352_8', name:'Fault Tolerance'},
        {id:17, subject_id:28, code:'CACS352_9', name:'Security'},
        {id:18, subject_id:29, code:'CAEC353_1', name:'Introduction'},
        {id:19, subject_id:29, code:'CAEC353_2', name:'Elasticity of Demand and Supply'},
        {id:20, subject_id:29, code:'CAEC353_3', name:'Theory of Consumer Behavior'},
        {id:21, subject_id:29, code:'CAEC353_4', name:'Cost and Revenue Curves'},
        {id:22, subject_id:29, code:'CAEC353_5', name:'Market Structure'},
        {id:23, subject_id:29, code:'CAEC353_6', name:'National income Accounting'},
        {id:24, subject_id:29, code:'CAEC353_7', name:'Money, Banking and International Trade'},
        {id:25, subject_id:30, code:'CACS354_1', name:'GUI Programming'},
        {id:26, subject_id:30, code:'CACS354_2', name:'Database Programming'},
        {id:27, subject_id:30, code:'CACS354_3', name:'JavaBeans'},
        {id:28, subject_id:30, code:'CACS354_4', name:'Servlets and JSP'},
        {id:29, subject_id:30, code:'CACS354_5', name:'RMI'},
        {id:30, subject_id:31, code:'CACS355_1', name:'Introduction'},
        {id:31, subject_id:31, code:'CACS355_2', name:'Internet Addresses'},
        {id:32, subject_id:31, code:'CACS355_3', name:'URLs and URIs'},
        {id:33, subject_id:31, code:'CACS355_4', name:'HTTP'},
        {id:34, subject_id:31, code:'CACS355_5', name:'URLConnections'},
        {id:35, subject_id:31, code:'CACS355_6', name:'Socket for Clients'},
        {id:36, subject_id:31, code:'CACS355_7', name:'Socket for Servers'},
        {id:37, subject_id:31, code:'CACS355_8', name:'Secure Socket'},
        {id:38, subject_id:31, code:'CACS355_9', name:'Nonblocking I/O'},
        {id:39, subject_id:31, code:'CACS355_10', name:'UDP'},
        {id:40, subject_id:31, code:'CACS355_11', name:'IP Multicast'},
        {id:41, subject_id:31, code:'CACS355_12', name:'Remote Method Invocation (RMI)'},
    ];

    static getChapterList(subjectId: number) {
        return this.chalterList.filter(x => x.subject_id == subjectId)
    }
}